# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    env: 
      key1: ${{secrets.WORKFLOW_TOKEN}} 
    runs-on: ubuntu-latest
    
    steps:
    - run: echo $key1
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: joschi/setup-jdk@v1
      with:
        java-version: '11'
        
        
    - name: Extract CODEGEN_VERSION
      if: success()
      run: |
        export VERSION=`cat pom.xml | grep "<version>" | head -n 1 |  awk -F'>' '{print $2}' | awk -F'<' '{print $1}'` && echo "::set-env name=CODEGEN_VERSION::${VERSION}.${GITHUB_RUN_NUMBER}"
        echo $CODEGEN_VERSION
        
    - name: Set ustack build number
      if: success()
      run: mvn versions:set versions:commit -DnewVersion="${CODEGEN_VERSION}"
          
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mvn clean install
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      run: |
        echo "<settings><servers><server><id>github</id><username>nuwansa</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
